### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by neokree** [Sipioteo/auto_localization#2]
The readme's section does not explain how the library works. 
It uses google translator? Or another service?

**Comment by Sipioteo** [comment]
It works with Google Translator
Da: "Fabio Biola" notifications@github.com
A: "Sipioteo/auto_localization" auto_localization@noreply.github.com
Cc: "Subscribed" subscribed@noreply.github.com
Data: Wed, 12 Feb 2020 08:06:27 -0800
Oggetto: [Sipioteo/auto_localization] How it works? (#2)

The readme's section does not explain how the library works.
It uses google translator? Or another service?

**Comment by neokree** [comment]
Ok thanks, could you add it in the README?

**Comment by Sipioteo** [comment]
Well yes, when I will have some time.
Da: "Fabio Biola" notifications@github.com
A: "Sipioteo/auto_localization" auto_localization@noreply.github.com
Cc: "Matteo Sipione" matteo@sipio.it,"Comment" comment@noreply.github.com
Data: Wed, 12 Feb 2020 08:13:21 -0800
Oggetto: Re: [Sipioteo/auto_localization] How it works? (#2)

Ok thanks, could you add it in the README?
