### ISSUE TITLE
does not return source language

### ISSUE THREAD

**Issue by fapcruz** [Sipioteo/auto_localization#3]
Hello,
I implemented the package and after changing some routines, I went to test another language,
changed from
BaseLanguage().setBaseLanguage("");
for
BaseLanguage().setBaseLanguage("en");
and no longer returns to the original language BaseLanguage().setBaseLanguage("pt");
have any guidance?
Thank you

**Comment by Sipioteo** [comment]
I made a lot of changes, if you find this issue again open a new issue.
