### ISSUE TITLE
How can we use TranslateBuilder offline

### ISSUE THREAD

**Issue by bhavesh350** [Sipioteo/auto_localization#4]
I want to save translated string locally, so that it do not required retranslate again.
How can I achieve that?

**Comment by Sipioteo** [comment]
If you check the code, I used sqlite to store the translated string as a cache. You don't have to do it yourself.

**Comment by bhavesh350** [comment]
Thank for your reply,
Yes I see that, but what I see with list as every cell view is recreating while scrolling, it again show in original language first then it is translating again. So I want to achieve in list once translated always be translated.

**Comment by bhavesh350** [comment]
Can you please tell me about the limit of the requests, because sometimes it gives some error code, that I searched and got to know about limit.

**Comment by Sipioteo** [comment]
That's strange, i will check ASAP.

**Comment by bhavesh350** [comment]
Hi @Sipioteo 
Did you get the issue?

**Comment by Sipioteo** [comment]
Hi @bhavesh350 
Sorry, try this new versione. I made a lot of changes.
